name: CI Builder
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main", "2.x" ]
  workflow_dispatch:

jobs:
  build:
    name: Build docs site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
 
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the site
        run: mkdocs build
